#!/bin/bash
set -euo pipefail

native_apps=(
  "Spotify"
  "Todoist"
  "Boostnote"
  "Slack"
  "Sequel Pro"
  "SourceTree"
  "Calendar"
  "Harvest"
  "Mail"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done

websites=(
  "https://oddhill.atlassian.net/secure/Dashboard.jspa"
  "https://circleci.com/dashboard"
  "https://oddhill.atlassian.net/wiki/discover/all-updates"
)

open -a "Google Chrome" --args --profile-directory="Sebastian"
for website in "${websites[@]}"; do
  open "$website"
done
