#!/bin/bash
set -euo pipefail

native_apps=(
  "Boostnote"
  "Todoist"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done

websites=(
  "https://github.com/SebbeLar"
  "https://twitter.com/"
)

open -a "Google Chrome" --args --profile-directory="Sebastian"
for website in "${websites[@]}"; do
  open "$website"
done